name: "Add Reviewer"
description: "Adds reviewer(s) to a PR. Run on pull_request opened."
branding:
  icon: "user-plus"
  color: "gray-dark"
inputs:
  reviewers:
    description: "Add list, pipe(|) separated."
    required: false
  reviewer_teams:
    description: "Teams to add."
    required: false
runs:
  using: "node16"
  main: "dist/index.js"