name: Main

on:
  workflow_call:
    inputs:
      reviewers:
        required: false
        type: string
      reviewer_teams:
        required: false
        type: string
    secrets:
      token:
        description: "GITHUB_TOKEN to be used."
        required: true
      PAT:
        description: "Personal Access Token that is needed if teams are to be added."
        required: false

jobs:
  add_reviewer_job:
    runs-on: ubuntu-latest
    name: Add reviewers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}
      - name: Add reviewers step
        uses: ./
        env:
          token: ${{ secrets.token }}
          PAT: ${{ secrets.PAT }}
        with:
          reviewers: ${{ inputs.reviewers }}
          reviewer_teams: ${{ inputs.reviewer_teams }}
